language: python

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36

addons:
  apt:
    packages:
      - libatlas-dev
      - liblapack-dev
      - python-numpy

install: pip install tox codecov

before_script:
    # configure a headless display to test plots
    # https://stackoverflow.com/questions/35403127
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3  # give xvfb some time to start

script: tox

notifications:
  email: false

after_success:
  - codecov
