language: python

env:
  # Defaults
  global:
    - COVERAGE=false
    - BLAS="mkl blas=*=mkl"  # Use Intel MKL by default
    - MKL_NUM_THREADS=1  # Enforce single thread
    - OPENBLAS_NUM_THREADS=1
    - NUMEXPR_NUM_THREADS=1

matrix:
  include:
  - python: 2.7
    env:
    - TOXENV=py27
    - BLAS="nomkl blas=*=openblas"
  - python: 3.5
    env:
    - TOXENV=py35
  - python: 3.6
    env:
    - TOXENV=py36
    - BLAS="nomkl blas=*=openblas"
  - python: 3.7
    env:
    - TOXENV=py37

  - os: osx
  language: generic
  env:
    - TOXENV=py36

addons:
  apt:
    packages:
      - libatlas-dev
      - liblapack-dev
      - python-numpy

before_install:
  # Skip if commit message contains [skip travis] or [travis skip]
  - COMMIT_MESSAGE=$(git show -s $TRAVIS_COMMIT_RANGE | awk 'BEGIN{count=0}{if ($1=="Author:") count++; if (count==1) print $0}')
  - if [[ $TRAVIS_PULL_REQUEST == false ]]; then COMMIT_MESSAGE=${TRAVIS_COMMIT_MESSAGE}; fi
  - if echo "$COMMIT_MESSAGE" | grep -E '\[(skip travis|travis skip)\]'; then exit 0 ; fi
  #
  # Show information about CPU running job to understand BLAS issues
  - sudo lshw -class processor

install:
  # Source recipe to install packages
  - pip install pytest>=3.6 pytest-xdist pytest-randomly tox codecov matplotlib wheel
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace
  - python setup.py develop

before_script:
  # Fix for headless TravisCI
  #   https://stackoverflow.com/questions/35403127
  - export DISPLAY=":99.0"
  - ci/before_script_travis.sh

script:
  - pytest sm2 --skip-slow
  #- tox

notifications:
  email: false

after_success:
  - codecov
