build: false
environment:
  matrix:
    - PYTHON_VERSION: 27
    - PYTHON_VERSION: 35
    - PYTHON_VERSION: 36

# follow pandas convention by only testing x64.  See comments in pandas'
# appveyor.yml file for how to run on x86
platform:
  - x64

build_script:
  - ps: Start-FileDownload "https://repo.continuum.io/miniconda/Miniconda$env:PY_MAJOR_VER-latest-Windows-$env:PYTHON_ARCH.exe" C:\Miniconda.exe; echo "Finished downloading miniconda"
  - cmd: C:\Miniconda.exe /S /D=C:\Py
  - SET MKL_NUM_THREADS=1
  - SET NUMEXPR_NUM_THREADS=1
  - SET OMP_NUM_THREADS=1
  - SET PATH=C:\Py;C:\Py\Scripts;C:\Py\Library\bin;%PATH%
  - conda config --set always_yes yes
  - conda update conda --quiet
  - ps: If ($env:SCIPY) { conda install numpy scipy=$env:SCIPY cython pandas pip nose patsy --quiet } Else {
        conda install numpy scipy cython pandas pip nose patsy --quiet }
  - pip install -r requirements.txt
  - pip install "pytest<4" pytest-xdist
  - python setup.py develop

test_script:
  # Remove xdist (-n auto) until warning reporting is working
  - pytest sm2
