build: false
environment:
  matrix:
    - PYTHON_VERSION: 27
    - PYTHON_VERSION: 35
    - PYTHON_VERSION: 36

# follow pandas convention by only testing x64.  See comments in pandas'
# appveyor.yml file for how to run on x86
platform:
  - x64

install:
  - python setup.py build_ext --inplace
  - pip install pytest
  - pip install -r requirements.txt

test_script:
  - pytest sm2
