build: false
environment:
  matrix:
    - PYTHON_VERSION: 27
    - PYTHON_VERSION: 35
    - PYTHON_VERSION: 36

# follow pandas convention by only testing x64.  See comments in pandas'
# appveyor.yml file for how to run on x86
platform:
  - x64

install:
  - pip install pytest matplotlib wheel
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace

# run bdist_wheel so we can collect artifact to make available on PyPI
build_script:
  - python setup.py bdist_wheel

test_script:
  - pytest sm2

artifacts:
  - path: dist\*.whl
