build: false
environment:
  matrix:
    - PYTHON_VERSION: 27
    - PYTHON_VERSION: 35
    - PYTHON_VERSION: 36
    - PYTHON_VERSION: 37

# follow pandas convention by only testing x64.  See comments in pandas'
# appveyor.yml file for how to run on x86
platform:
  - x64

install:
  # cancel older builds for the same PR
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }

  - pip install pytest pytest-xdist pytest-randomly matplotlib wheel
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace

build_script:
  # Search for [appveyor skip] or [skip appveyor] and exit if found in full commit message
  - ps: $commit=$env:APPVEYOR_REPO_COMMIT_MESSAGE + $env:APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED
  - ps: $skip_appveyor=$commit.Contains("[skip appveyor]") -Or $commit.Contains("[appveyor skip]")
  - ps: If ($skip_appveyor) { echo "[skip appveyor]"; Exit-AppVeyorBuild }
  #
  # Show information about CPU running job to understand BLAS issues
  - wmic cpu get caption, name, numberofcores
  #
  # run bdist_wheel so we can collect artifact to make available on PyPI
  - python setup.py bdist_wheel

test_script:
  - pytest sm2

artifacts:
  - path: dist\*.whl
